---
abstract: 'helper module to retrieve data from pdf2json'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDF-pdf2json
requires:
  Alien::pdf2json: 0
  File::Temp: 0
  JSON::MaybeXS: 0
  Path::Class: 0
  strict: 0
  warnings: 0
version: 0.001
